const UserActionTypes = {
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	LOGOUT_START: "LOGOUT_START",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAILURE: "LOGOUT_FAILURE",
	SELECT_YEAR: "SELECT_YEAR",
	LOADING_START: "LOADING_START",
	LOADING_END: "LOADING_END"
}

export default UserActionTypes;