const ClassActionTypes = {
	SET_CLASS: "SET_CLASS",
	REMOVE_CLASS: "REMOVE_CLASS",
	SET_CLASSES_START: "SET_CLASSES_START",
	SET_CLASSES: "SET_CLASSES",
	REMOVE_CLASSES: "REMOVE_CLASSES",
	SET_CLASSES_FAIL: "SET_CLASSES_FAIL",
	SET_TIMETABLE: "SET_TIMETABLE",
	REMOVE_TIMETABLE: "REMOVE_TIMETABLE",
	SET_NOTIFICATION: "SET_NOTIFICATION",
	REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
	SET_LEAVE_UPDATED: "SET_LEAVE_UPDATED",
	REMOVE_LEAVE_UPDATED: "REMOVE_LEAVE_UPDATED"
}

export default ClassActionTypes;